config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection { post :import }
  end

  root 'blogs#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :categorizations
  has_many :categories, through: :categorizations

  # CSデータ読込処理
  #
  # @param file [string] CSVデータのファイルパス
  # @return void
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      blog = Blog.new(
        title: row[BlogModelConstants::HEADER_BLOG_TITLE],
        content: row[BlogModelConstants::HEADER_CONTENT],
        created_at: Time.zone.parse(row[BlogModelConstants::HEADER_CREATED_AT]),
        updated_at: Time.zone.parse(row[BlogModelConstants::HEADER_UPDATED_AT])
      )

      # カテゴリをカンマ区切りで配列化
      categories = row[BlogModelConstants::HEADER_CATEGORY].split(',').map(&:strip)

      categories.each do |category_name|
        # 既存のカテゴリが無ければ生成
        category = Category.find_or_create_by(name: category_name)
        blog.categories << category
      end

      blog.save
    end 
  end
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :blog
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizations
  has_many :blogs, through: :categorizations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # Blog全件取得
  def index
    @blogs = Blog.includes(:categories)
  end

  # POST /blogs/import
  # CSVデータ読込
  def import
    Blog.import(params[:file])
    redirect_to root_path
  end

  # GET /blogs/1
  # 該当するルーティングが無い為処理なし
  def show
    
  end

  # GET /blogs/1/edit
  # 該当するルーティングが無い為処理なし
  def edit

  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  # 該当するルーティングが無い為処理なし
  def update
    
  end

  # DELETE /blogs/1 or /blogs/1.json
  # 該当するルーティングが無い為処理なし
  def destroy
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td>
      <% blog.categories.each do |category| %>
        <%= category.name %>
      <% end %>
    </td>
    <td><%= l blog.created_at %></td>
    <td><%= l blog.updated_at %></td>
  </tr>
</div>

app/views/blogs/_form.html.erb
<%= form_tag import_blogs_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "CSVインポート" %>
<% end %>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blogs</h1>
<%= link_to "CSV Import", new_blog_path %>

<div id="blogs">
  <table border>
    <tr>
      <th>BlogTitle</th>
      <th>BlogContent</th>
      <th>Category</th>
      <th>Creatted_at</th>
      <th>Updated_at</th>
    </tr>
    <% @blogs.each do |blog| %>
      <%= render blog %>
    <% end %>
  </table>
</div>

app/views/blogs/new.html.erb
<h1>Upload CSV</h1>
<%= render "form", blog: @blog %>
<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>